### ISSUE TITLE
Command line importer problems

### ISSUE THREAD

**Issue by ewels** [s-andrews/SeqMonk#10]
Hello,

I just tried using the `seqmonk_import` in the wild for the first time and got this error:

```
$ perl /sw/apps/bioinfo/SeqMonk/1.36.0/irma/seqmonk_import --outfile pname_alignments.smk --genome kjsnd/sdfkjn *bam

Memory ceiling is 10240
Raw physical memory is 257683
Correcting for VM actual requested allocation for 10240 is 11520
Reading Genome
Genome loaded for kjsnd sdfkjn
Parsing Data
Parsing P2457_107_R1_val_1_bismark_bt2_pe.deduplicated.bam
Parsing P2457_108_R1_val_1_bismark_bt2_pe.deduplicated.bam
Parsing P2457_109_R1_val_1_bismark_bt2_pe.deduplicated.bam
Parsing P2457_110_R1_val_1_bismark_bt2_pe.deduplicated.bam
Parsing P2457_111_R1_val_1_bismark_bt2_pe.deduplicated.bam
Parsing P2457_112_R1_val_1_bismark_bt2_pe.deduplicated.bam
java.io.IOException: Failed to rename temporary file
        at uk.ac.babraham.SeqMonk.DataWriters.SeqMonkDataWriter.run(SeqMonkDataWriter.java:271)
        at java.lang.Thread.run(Thread.java:745)
```

Any ideas?

**Comment by s-andrews** [comment]
Can you try putting./ in front of the outfile name and seeing if that works.

**Comment by ewels** [comment]
Ok, running now, will let you know how it goes. There was a permissions error with the scripts too, don't know if that could have anything to do with it? (That's why I prefixed the command with `perl`).

**Comment by ewels** [comment]
It worked! Is it trying to write the resulting SeqMonk project file to somewhere random?

**Comment by s-andrews** [comment]
I suspect it tried to write it to your system temp directory.  Need to work out how to not make that happen.

**Comment by s-andrews** [comment]
I found the cause for this.  When you create a File object from a relative path then it's stored only as a relative path internally, even though it reports a proper looking path when you print it out.  The effect of this though is when we call getParent on it to get the folder to write the temp file to, then returns null (because just a file name doesn't have a parent) and the temp file gets made in the default system temp dir and stuff breaks from there.

The fix is to call getAbsoluteFile() as soon as we create the File object to force the interpretation of the relative path and then everything works as expected.
