### ISSUE TITLE
Vistory claims that filtering was done on a sub list even when it was done on ‘All Probes’

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#190]
Filtering ‘All Probes’ produces a vistory event, for example:

![image](https://user-images.githubusercontent.com/27807527/58971214-dccf1c80-87b2-11e9-90f0-12243c3a89b8.png)
 
If you then keep the Filtering window open, highlight a different probe list in the Probe List window, and apply another filter, the actual filtering will be done on ‘All Probes’, but the vistory will record it as being filtered from a sub list.

![image](https://user-images.githubusercontent.com/27807527/58971242-ece6fc00-87b2-11e9-81d1-eb9056cea2f0.png)

**Comment by s-andrews** [comment]
Yeah, this isn't actually a vistory issue, it's true for the description in the list too.  The problem is that the call to get the description re-pulls the active list rather than taking it from the event which generated the list in the first place.  There's probably a really simple fix, but it might need to be implemented in every probe list.
