### ISSUE TITLE
Feature Request: Options for directories on startup

### ISSUE THREAD

**Issue by code4dna** [s-andrews/SeqMonk#232]
It would be nice to have options to specify the cache, genomes, default data and default save directories when launching seqmonk on Linux. This would be useful when running on an HPC compute node where a unique temp directory is created at runtime and the disk space in the user's home directory is limited. Also useful to have a flag to not check for updates since HPC compute nodes are often not connected to the internet.
Thanks,

**Comment by s-andrews** [comment]
If you are running seqmonk for the first time then it should prompt you to select a suitable cache and genomes directory (which will suggest using your home directory, but you can change it from the prompt screen).

Once in seqmonk these values can be changed under Edit > Preferneces, but I think it requires a restart for them to take effect.  I think we also test the presence and write status of the directories on the welcome screen and will warn if there are any problems.

Is there a use case I'm missing with these options?  Would you want to change them per-session for some reason?  I suppose we could have a flag which ignored any existing seqmonk_prefs.txt file and forced a fresh configuration, but that would wipe out all of the preferneces.  You could also use something like:

```alias seqmonk "rm ~/seqmonk_prefs.txt && seqmonk"``` 

(I haven't tested that but you get the idea) - so that it wipes your saved preferences before launching.

**Comment by code4dna** [comment]
I see that I can do all this by creating the ~/seqmonk_prefs.txt for new users before seqmonk is launched based on the copy that was created in my home directory.
