### ISSUE TITLE
Support CellRanger-style sampleID within readID

### ISSUE THREAD

**Issue by FelixKrueger** [s-andrews/SeqMonk#249]
Dear developer,

We are now more and more frequently running into the issue that experimentalists are using transposases or similar technologies to multiplex a ridiculous number of samples. In fact, there are so many samples that we are running into issues with how many file handles the OS allows to read from or write to at any one time.

We have therefore been talking about writing the demultiplexing information into the readID instead, currently in for the form of `sampleID:201124_triplex_-dox_plate1_K36me3_A08` as the last element of the readID. Could we please get an import filter that will split out the data into different samples based on this `sampleID`?

Here are a few example lines from a BAM file:

```
HWI-D00436:531:HJYW5BCX3:1:1101:1744:1992_1:N:0:ATTACTCG:GTTCATGG:TATGGCAC:AGGCGAAG:sampleID:201124_triplex_-dox_plate1_K36me3_A08	99	5	74873603	42	76M	=	74873746	219	ACCCAAGACTGGGCATTTTACAAAAGAAAGAGGTTTAATGGACTTACAGTTCCACGTGGCTAGGGAGGGCCTCACA	DDDDDIIIIIIIIIHIIIIIIIIIIIGIIIIIIDGHIIHIIIIIIIIIIIIIIIIHIIIIIIIIIIGGHIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i
:0	NM:i:0	MD:Z:76	YS:i:0	YT:Z:CP
HWI-D00436:531:HJYW5BCX3:1:1101:1744:1992_4:N:0:ATTACTCG:GTTCATGG:TATGGCAC:AGGCGAAG:sampleID:201124_triplex_-dox_plate1_K36me3_A08	147	5	74873746	42	76M	=	74873603	-219	TGTGCAGAGAAACTCCCCTCTTTAAAACCATCAGATCTTGTGAGACGCATTCACTATCACGAGAACAGCACAGGAA	HHIIIIIIIIIIIIIIHIIHIHIIIIIIIIIGIIIIIIHIIIIIIHIIHFGIIIIHIIIIIIIIIIIIIIICDDDD	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i
:0	NM:i:0	MD:Z:76	YS:i:0	YT:Z:CP
HWI-D00436:531:HJYW5BCX3:1:1101:1679:1994_1:N:0:TCCGGAGA:GAGCAGTA:TATGGCAC:GGCTCTGA:sampleID:201124_triplex_-dox_plate1_K27ac_A02	99	16	51829702	42	76M	=	51829808	182	GTTGTGCACACAGTAGGAGCTCAGCTATGAACTGAACACAGCTGCCTACCTGATGACACAGGGGGTTGCTATATAT	DDDDDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIIIIIIIIIIIIIIIIF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i
:0	NM:i:0	MD:Z:76	YS:i:0	YT:Z:CP
HWI-D00436:531:HJYW5BCX3:1:1101:1679:1994_4:N:0:TCCGGAGA:GAGCAGTA:TATGGCAC:GGCTCTGA:sampleID:201124_triplex_-dox_plate1_K27ac_A02	147	16	51829808	42	76M	=	51829702	-182	AATTTATGACCATTTATGGGAAGACAAAACAATGTTTTCTGCAAGGTATTTCATTCTAATCACTGGAATCATAGTC	HIIIIHHHHE?HGCEHIHFHIIHHHHIHECIIIIHHIGIHFHIIIHIHHHGIIHIIHIIIIIIHHIIIIHIDCDDD	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i
:0	NM:i:0	MD:Z:76	YS:i:0	YT:Z:CP
HWI-D00436:531:HJYW5BCX3:1:1101:1972:1901_1:N:0:TCCGGAGA:TCGTTCGT:TATGGCAC:GGCTCTGA:sampleID:201124_triplex_-dox_plate1_K27ac_A06	83	8	70074863	42	76M	=	70074710	-229	ATTGCCAATTCTTTAAAGCTGCCTGTCTTTCACATAAGAAGTAAAATCGTATTCTAATTGCCTTTTAGTCATTTAC	GIIIIHIIIIIIIIIHHIHHIIIIIIIIIIIIIIIIIIIIIHIIIIHIIIIHIIIIIGIIIIIHIIIIIIHDDDDD	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i
:0	NM:i:0	MD:Z:76	YS:i:-6	YT:Z:CP
```

I have placed a sample file into this folder:

```
group/Felix/SeqMonk_addFeature
```

Many thanks.

**Comment by s-andrews** [comment]
Dear Requestor,

In theory this shouldn't be too hard.  The samples would be identified by a name taken from after the last colon in the read ID, right?

The big potential problem with this is going to be memory usage.  Data import is already nasty as we have to hold the data for all chromosomes in memory together until we can split and sort it.  Adding this means we'll be doing that for multiple samples at once which will greatly inflate memory usage.  The cache folder is also going to get icky with the number of temp files if we're dealing with large numbers of samples so we might need to look at putting folders in per sample to cut down on the congestion, and maybe writing the data into a single file with an offset rather than having separate files per chromosome.

Let me take a look...

**Comment by s-andrews** [comment]
OK, so I've got an initial implementation which works with the example data and creates 281 new datasets.  There are going to be some performance issues with this though.

Firstly putting that many data sets into the chromosome view is *slow*.  There's just a lot to calculate.  We might be able to optimise this by just skipping read drawing where there isn't space to draw even a single line of reads which might make a huge difference.

Another option would be that when we import data from embedded files that we create a replicate set per BAM file and put them into that, and then add the replicate set to the view?

I also want to look at the cache folder structure since we're going to end up with around 9000 cache files in one folder which is going to get nasty.  It might be better to make a folder per dataset and put the cache files for that dataset into there which will still mean the same number of files, but would cut down on the files per directory.  Even better would be if we could put all of the cached data for one dataset into a indexed file and then read from the appropriate offset when reading it back.  Not sure how easy that would be though.

**Comment by s-andrews** [comment]
Actually the slowness isn't related to the cache (at least not just that).  It's something to do with the calculation which happens when the track height changes.  It might just be the read assignment for 283 tracks which is slow, but it could be something more trivial so it might be worth a look in case there's an easy win.

**Comment by s-andrews** [comment]
It's fixed!!! You can now view hundreds of tracks and resize them almost instantly.  The issue what that the track height layout calculation is quite slow (well a couple of hundred milliseconds) but when you drag the main window divider that function gets called for every pixel the divider moves, even though you never see the intervening layouts.  That caused massive slowdowns.

I've now changed it so that when you click on the divider it swaps out the chromosome view for a blank panel, and then swaps it back when you release the mouse.  This means that the complicated layout is only called once and the screen update is almost instantaneous.

We're still going to get into performance issues with super large numbers of datasets and cache reloads, but at least one problem is fixed.

I'm going to close this now as the feature itself is now working as expected.  Anything else is a more general performace problem.

**Comment by FelixKrueger** [comment]
That's great, thanks very much!
