### ISSUE TITLE
Building a custom genome fails for genomes with a lot of scaffolds

### ISSUE THREAD

**Issue by FelixKrueger** [s-andrews/SeqMonk#25]
I tried importing the wheat genome from the FastA file `Triticum_aestivum.TGACv1.dna.toplevel.fa` but it seems to hang after reading the names of the 735943 scaffolds... Thanks.

**Comment by s-andrews** [comment]
This is due to the poor scalability of updating large tables.  At the moment the table model is refershed every time a new scaffold is found.  If you have lots of scaffolds (like here), the number of updates means the progress gets exponentially slower.

I think the solution is going to be to not update the table incrementally but just use a standard progress bar and then do a single update of the table at the end.  Not as pretty, but more practical.
