### ISSUE TITLE
When customizing a genome, the regionname in the fasta file is not read correctly

### ISSUE THREAD

**Issue by Shokusei** [s-andrews/SeqMonk#267]
If I load a fasta file whose header name is ChromosomeX, the regionname is read as omosomeX. I want it to be read as chromosomeX.
![image](https://github.com/s-andrews/SeqMonk/assets/93243583/0cd07de2-2147-4342-bee9-2575581aa7a9)
![image](https://github.com/s-andrews/SeqMonk/assets/93243583/9b62f825-e286-4690-b43b-87284a7e12c3)

**Comment by s-andrews** [comment]
Yeah, I can see that's a problem.  SeqMonk tries to work around the common problem that for many genomes there are versions with names like 1,2,3 and other identical sequences called chr1,chr2,chr3 so when importing read data it will try both the sequence name directly and the name with the chr removed which generally makes things work.

Because the import of reads only tries removing a chr it will only work if the actual chromosomes in the file are called 1,2,3 and not chr1,chr2,chr3, so when creating a custom genome it removes chr from the front of any sequence names, which is what you're seeing.

If you create the genome with the options specified then reads with Chromosome1 as their name will be imported correctly, but I get that the names on the display will look odd.

The simplest fix is to create your genome with the truncated names, then go into your genomes older and find the genome you created.  In there is a text file called chr_list.  If you edit that you will see the chromosome names and you can change these back to the full names.

When you next reload your genome you should see the updated names.

Let me know if this does what you need.
