### ISSUE TITLE
Installation in a linux/HPC R environment

### ISSUE THREAD

**Issue by robin-sto** [s-andrews/SeqMonk#268]
Hello,

I am trying to determine the correct way to install seqmonk in a hpc cluster environment where the modules and programs are centralized.  It sounds like the program has to be installed locally in order to be used.  We typically load modules when running programs.  Is it possible to use seqmonk in this type of environment?

**Comment by s-andrews** [comment]
Yes, that's how we run it on our cluster.  The seqmonk install on linux is just a tar file you untar and then run the ```seqmonk``` launch script.  It's dead easy to turn into a module.  The only complexity is that it relies on R so you'd need to add a dependecy to the R module so that was loaded alongside it, and you'd need to ensure that the required R packages were globally installed in the base R image so that each user didn't need to install them themselves.

For the record this is our module file for seqmonk

```

$ cat 1.48.2.devel
#%Module 1.0
##
##
proc ModulesHelp { } {

        puts stderr "\t Use seqmonk 1.48.2.devel"
}

module-whatis   "Sets your PATH and environment variables for use with seqmonk 1.48.2.devel"

module load R
prepend-path    PATH /bi/apps/seqmonk/1.48.2.devel

```
