### ISSUE TITLE
Correlation Table Heatmap: Follow-up requests

### ISSUE THREAD

**Issue by ewels** [s-andrews/SeqMonk#27]
Following on from #24.. Firstly - many thanks for the new table / plot! It works really nicely and is exactly what I had in mind.

Having had a quick play, I have a couple of minor suggestions:

1. Fixed font-sizes
    * The font-size seems to scale with vertical height, which means that the only way you can get in longer sample names / decimal places is by making the plot wide and short.
2. Tick-box for scale
    * As these are correlation scores, it'd be nice to be able to have the colour scale work from 0-1 if requested. 
3. Configurable colour scheme
    * Naturally ;)
4. Diagonal `1.0` colouring
    * Seems a little unfair that these don't get coloured in the same syntax as the others, given that they do have values (even if they're a little uninformative).
5. Different behaviour for sample labels than for numbers
    * I'm pretty sure that you implemented it like this for a good reason, so feel free to ignore this, but...
    * The data labels also disappear when the numbers get squashed too much
    * It would be nice if the left-hand-side labels at least had a little more space
    * Top side labels could be angled at 45 degrees? But that's probably nasty to code.

Anyway, loving the new feature generally, thanks again! 🎉 

Phil

**Comment by s-andrews** [comment]
1 and 5 are basically the same thing (scaling of text).  The core limitation here is that in this implementation the whole plot has to fit on screen so if you have long text for each box then you either have to truncate it or make it smaller until it fits.  Since the whole things is a grid then the width is just equally divided into the number of stores+1, we then scale the text within that box.

I suppose there are some options for how to treat this:

1) We could make the leftmost column wider to try to accommodate more text
2) We could scale the text to either the height or the width, whichever is smaller 

Given that we're going to run out of space quite a lot of the time the compromise I went for is that you can mouse over any point of the plot to get the full text of the box in a tooltip.  This should make it pretty easy to figure out what's what interactively.  For presentation you can export an SVG and go nuts with rearranging things however you like.

I might take a look at expanding the left hand text a bit more.  45 degree labels for the top are the spawn of satan - not doing that (I'd be thrown off my own figure design course!) :-)

Tick box for scale - correlation goes from -1 to 1, not 0 to 1 :-) I guess we could have this as an option.  I don't think it makes any sense to have any further options though.  Correlation in most NGS is normally horribly confounded though so looking at absolute rather than relative correlation isn't normally all that informative.

Diagonal colouring - not sure what to suggest here.  Diagonal values offer literally no information since they're always 1 by definition.  Including them in the data will just mess up the scaling (unless you're using an absolute scale).  What would you want to see there?

Colouring - the plot picks up the current default gradient set in the display preferences so it is kind of configurable.  I should probably make this changeable per plot but I ran out of time (after having to rewrite the whole drawing code since the original one didn't scale to hundreds of samples).  Will look into this.

**Comment by ewels** [comment]
> _We could make the leftmost column wider to try to accommodate more text_

Yup, that was pretty much what I had in mind. Just double the width or something would be a big help.

> _We could scale the text to either the height or the width, whichever is smaller_

Also good - can you not set a fixed height for the text and just scale the width only though? Or is this difficult?

> _You can mouse over any point of the plot to get the full text of the box in a tooltip._

Cool! I didn't realise this..

> _Diagonal colouring_

Yeah fair enough. In my test plot all of my correlations were > 0.9 and it just looked a bit odd having a white diagonal down the middle. If it were 1 then it would have looked kind of like a HiC heatmap somehow. White is fine :)

> _Colouring - the plot picks up the current default gradient_

Also didn't figure this out - works fine for me as long as it is possible to change it..
