### ISSUE TITLE
Failed to Launch Seqmonk; SeqMonk process failed to launch

### ISSUE THREAD

**Issue by traini82** [s-andrews/SeqMonk#32]
Hello,

Need some help launching the windows version of Seqmonk  v1.38.2. We first confirmed java x64 install  C:\Users\tra00>java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
But when we double-click SeqMonk.exe we see a consistent failed memcheck error (attached). Please advise
[MonkSeq cmd log.txt](https://github.com/s-andrews/SeqMonk/files/1145523/MonkSeq.cmd.log.txt)
[MonkSeq cmd log.txt](https://github.com/s-andrews/SeqMonk/files/1145526/MonkSeq.cmd.log.txt)

**Comment by s-andrews** [comment]
That looks like you're actually missing part of the installation.  The program is looking in D:\Downloads\seqmonk_v1.38.2\SeqMonk but isn't finding the file D:\Downloads\seqmonk_v1.38.2\SeqMonk\uk\ac\babraham\Utilities\ReportMemoryUsage.class

One thing to check is that you've definitely uncompressed the zip file you downloaded.  Windows has an odd sort of virtual view of zip files so they kind of look like a normal folder but it's just uncompressing the files on the fly.  This means that you can navigate to the exe file and double click it but because the rest of the installation isn't actually uncompressed then everything fails.  Given that your install is in your downloads I kind of suspect this might be what's happening.  Can you check that the install files are definitely extracted from the zip file you downloaded.

If that's OK then have a look for the file which is missing and see if you can see it in windows explorer.  If it's missing then just go back to the seqmonk project page and re-download the install, it might have been that you got a partial download last time.

Let me know how you get on.

**Comment by traini82** [comment]
Hello Simon,

Downloaded a fresh copy to my primary drive (rather than the secondary I had used earlier) and its working. Not sure whether the culprit was the file or the fact it wasn't on the root drive but either way I look forward to exploring SeqMonk functions. Thanks for the quick response and great support.

Chris

**Comment by s-andrews** [comment]
Great, glad to hear you're up and running.  Let me know if you hit any other problems.
