### ISSUE TITLE
Launch by clicking project

### ISSUE THREAD

**Issue by StevenWingett** [s-andrews/SeqMonk#57]
It would be convenient if a SeqMonk project could be launched by directly double-clicking the project rather then opening SeqMonk and then opening the project from SeqMonk.

**Comment by s-andrews** [comment]
This is only partly within our control.  The bit we can do is to make it so that if you pass a project name to the seqmonk launcher that it will then open it - and much of that code is in place already.

The association with a file extension is a function of the operating system and as we don't have an actual install procedure (just an unzip) we don't get an opprotuntiy to set registry keys or whatever it is that OSX and the myriad linux desktops use, so that part might have to be more manual.

**Comment by s-andrews** [comment]
So the main seqmonk java class has this functionality already, so it's just a matter of making sure the upstream launchers pass any file name they're given along correctly.

**Comment by s-andrews** [comment]
I've now patched both the windows and unix launchers to make this work.  I've tested the file association on windows and it seems to work OK so this should be done.

I'll have to make a small tutorial to show how to set up the file association so this works automatically, but for now this all looks good.
