### ISSUE TITLE
feature displays incorrectly when zoomed in 

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#59]
Zooming in to the right end of a feature moves the end right up to the edge of the window. Zooming out it snaps back into its correct place. Seems to affect all right ends of gene features (and a custom feature) but not mRNA. Hovering over the extended bit doesn't highlight it. Genome is GRCm38.
![extended_feature](https://user-images.githubusercontent.com/27807527/35522541-8c076928-0514-11e8-8205-303aa585fd8a.PNG)
![correct_feature_ends](https://user-images.githubusercontent.com/27807527/35522542-8e0bbed6-0514-11e8-924e-35daf3245532.PNG)

**Comment by s-andrews** [comment]
I can't replicate this on the latest seqmonk on windows.  Nothing has changed in the code which draws this view for ever, so I'm not sure why the result is different.

![not_a_bug](https://user-images.githubusercontent.com/8157923/35522816-4013fb98-0515-11e8-94e3-c24b9d105324.png)

**Comment by s-andrews** [comment]
I can reproduce this on linux, but not windows or OSX.  The odd thing is that the larger feature only responds to mouseOver when you're over the bit which should be drawn, and not the rest.  Since the mouseOver and the drawing use the same coordinates the two should match so this suggests a core java drawing bug.

I can confirm this by exporting the view into a png file.  That uses exactly the same component which is drawn on screen and just renders it through the PNG renderer instead of generating X11 events.  There's no way the two should ever be different (it's litereally the same view), but the PNG version doesn't show the extra box.  This pretty much nails this as a  core java drawing bug on linux.  If we can reduce this to a simple test case we can report it as a bug to Oracle, but there's nothing to fix in SeqMonk I'm afraid.

![bug_or_not](https://user-images.githubusercontent.com/8157923/35523420-b8166e2c-0516-11e8-808e-244d3f8ab2e7.png)
