### ISSUE TITLE
Selection of a specific set of samples in the RNA-seq QC plot

### ISSUE THREAD

**Issue by ChristelKrueger** [s-andrews/SeqMonk#82]
At the moment it is tricky to select (or highlight) only a few samples from a larger list of samples for the RNA-seq QC plot. This plot does not pick up from the display (where you could more easily select a subgroup), nor does it offer the option of searching for sample names in the list. Also, the sample selection window is not scrollable so file names get truncated.

**Comment by s-andrews** [comment]
It's a bit incongruous with the rest of the UI that the RNA-Seq QC plot actually asks you which samples to plot.  The standard way this works for plots is that they just take the samples which are currently in the view, and keep them in that order.

I've therefore patched the code so that this is the behaviour.  This will make it easy to plot specific samples as it can use the existing controls to add / remove tracks.
